In [2]:
import numpy as np

In [3]:
from numpy import linalg

Задача 1. Сумма векторов  
Даны два вектора a и b одинаковой длины.
Посчитайте их сумму поэлементно.
Посчитайте скалярное произведение.
Выведите оба результата.


In [12]:
a = np.array([1, 6, 8, 42])
b = np.array([4, 6, 8, 1])

In [13]:
a * b

array([ 4, 36, 64, 42])

In [14]:
np.prod(a*b)

np.int64(387072)

Задача 2. Маскирование массива  
Дан массив температур за 30 дней: temp = np.random.randint(-5, 35, size=30).
Выведите все температуры выше 20 градусов.
Выведите индексы этих температур.

In [15]:
temp = np.random.randint(-5,35,size=30)
temp

array([22, 11, 34,  6, 30, 33, 30, -4, 20, 25, 29,  2, 31,  5,  6, -5, 13,
       24,  3, 27,  1, 11, -3, 20, 32, 20, 23, 33, 16,  7], dtype=int32)

In [19]:
mask = temp > 20
index_mask = np.where(mask)
index_mask

(array([ 0,  2,  4,  5,  6,  9, 10, 12, 17, 19, 24, 26, 27]),)

Задача 3. Работа с матрицами  
Создайте матрицу A размером 3×3 с числами от 1 до 9.  
Найдите сумму элементов каждой строки.  
Найдите сумму элементов каждой колонки.  
Транспонируйте матрицу и выведите результат.


In [20]:
M = np.arange(1,10).reshape(3,3)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
M.sum(axis=0)

array([12, 15, 18])

In [30]:
M.sum(axis=1)

array([ 6, 15, 24])

In [23]:
M.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Задача 4. Срезы и индексация  
Создайте вектор из чисел от 0 до 19.  
Выведите каждый третий элемент.  
Выведите вектор в обратном порядке.  
Выведите элементы на нечетных позициях.


In [46]:
c = [ 5,  7,  6,  13,  6,  4,  7,  2,  5,  3, 6, 4, 11, 74, 36, 98, 7, 19, 8, 21]
c

[5, 7, 6, 13, 6, 4, 7, 2, 5, 3, 6, 4, 11, 74, 36, 98, 7, 19, 8, 21]

In [47]:
c[::3]

[5, 13, 7, 3, 11, 98, 8]

In [48]:
c[::-1]

[21, 8, 19, 7, 98, 36, 74, 11, 4, 6, 3, 5, 2, 7, 4, 6, 13, 6, 7, 5]

In [49]:

c[::2]

[5, 6, 6, 7, 5, 6, 11, 36, 7, 8]

In [50]:
indices_every_third = np.arange(0, len(c), 3)
indices_every_third

array([ 0,  3,  6,  9, 12, 15, 18])

In [52]:
indices_invers = np.arange(len(c), -1, -1)
indices_invers

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [55]:
indices__odd_positions = np.arange(1, len(c), 2)
indices__odd_positions

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Задача 5. Статистика массива  
Дан массив data = np.random.randint(0, 100, size=50).  
Найдите среднее и стандартное отклонение.  
Выведите элементы меньше среднего.  
Выведите элементы выше среднего + 1*стандартное отклонение.  

In [56]:
data = np.random.randint(0, 100, size=50)
data

array([94, 12,  9, 46,  0, 16, 20, 30,  6, 85, 46,  5, 42, 96, 45, 89, 24,
       97, 24, 44, 92, 66,  6, 61, 15, 20, 89, 86, 58,  7, 94,  5,  3, 25,
       51, 56, 61, 42, 41, 39, 95, 54, 29, 59, 77, 97, 10, 38, 14, 36],
      dtype=int32)

In [60]:
np.mean(data)

np.float64(45.12)

In [61]:
np.std(data)

np.float64(31.06614877966048)

In [63]:
mask = data < np.mean(data)
data[mask]

array([12,  9,  0, 16, 20, 30,  6,  5, 42, 45, 24, 24, 44,  6, 15, 20,  7,
        5,  3, 25, 42, 41, 39, 29, 10, 38, 14, 36], dtype=int32)

In [68]:
# Выведите элементы выше среднего + 1*стандартное отклонение
mask = data < np.mean(data)
s = (data[mask] + 1) * np.std(data)
s

array([ 403.85993414,  310.6614878 ,   31.06614878,  528.12452925,
        652.38912437,  963.05061217,  217.46304146,  186.39689268,
       1335.84439753, 1429.04284386,  776.65371949,  776.65371949,
       1397.97669508,  217.46304146,  497.05838047,  652.38912437,
        248.52919024,  186.39689268,  124.26459512,  807.71986827,
       1335.84439753, 1304.77824875, 1242.64595119,  931.98446339,
        341.72763658, 1211.57980241,  465.99223169, 1149.44750485])

Задача 6. Векторизация  
Напишите функцию f(x), которая возвращает 1, если x >= 0 и 0 иначе.  
Примените эту функцию к массиву np.array([-5, -2, 0, 3, 7]) с помощью векторизации.


In [69]:
def f(x):
    if x >= 0:
        return 1
    else:
        return 0

f_vect = np.vectorize(f)
f_vect(np.array([-5, -2, 0, 3, 7]))



array([0, 0, 1, 1, 1])

Задача 7. Изменение формы массива  
Создайте массив arr = np.arange(12).  
Преобразуйте его в матрицу 3×4.  
Выведите первую строку и последний столбец.  
Сделайте копию массива и поменяйте в ней первый элемент. Убедитесь, что исходный массив не изменился.


In [70]:
arr = np.arange(12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
arr.reshape(3,4)[0, :]

array([0, 1, 2, 3])

In [79]:
arr.reshape(3,4)[:, -1]

array([ 3,  7, 11])

In [85]:
arr_1 = np.copy(arr.reshape(3,4))
arr_1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
arr_1[0, 0] = 15
arr_1

array([[15,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Задача 8. Линейная алгебра  
Создайте матрицу A = np.array([[2,1],[3,4]]) и вектор b = np.array([5,6]).  
Решите систему уравнений Ax=b.  
Найдите определитель матрицы A.  
Найдите собственные значения матрицы.


In [90]:
A = np.array([[2, 1], [3,4]])
b = np.array([5,6])
x = np.linalg.solve(A, b)
x

array([ 2.8, -0.6])

Задача 9. Объединение массивов  
Создайте два массива:  
a = np.array([[1,2],[3,4]])  
b = np.array([[5,6]])  
Соедините их по строкам.  
Соедините их по столбцам.  
Повторите массив a 3 раза по строкам и по столбцам.


In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5,6])
a.shape, b.shape

((2, 2), (2,))

In [5]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.hstack((a, b.reshape(-1,1)))


array([[1, 2, 5],
       [3, 4, 6]])

In [10]:
b.reshape(-1,1)

array([[5],
       [6]])

In [11]:
b.reshape(2,1)

array([[5],
       [6]])

In [14]:
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

Задача 10. Фильтрация и логические условия  
Создайте массив случайных чисел от 0 до 20 размера 10.  
Проверьте, есть ли хотя бы одно число > 15 (any).  
Проверьте, все ли числа > 5 (all).  
Выведите элементы, которые меньше среднего + 2.


In [19]:
a = np.random.randint(0, 20, 10)
a

array([15,  8, 16, 18,  7,  5, 18, 16,  0, 10], dtype=int32)

In [16]:
mask = a > 15
a[mask]

array([17, 19], dtype=int32)

In [21]:
if (a > 15).any():
    print("Есть числа больше 15")
else:
    print("Нет чисел больше 15")

Есть числа больше 15


In [23]:
if (a > 5).all():
    print("Все больше 5")
else:
    print("Не все числа больше 5")

Не все числа больше 5


In [28]:
np.mean(a)

np.float64(11.3)

In [29]:
mask = a > np.mean(a)
a[mask] + 2

array([17, 18, 20, 20, 18], dtype=int32)





3. Индексация по условию  

Дан массив оценок студентов. Выведите индексы студентов, у которых оценка больше среднего + 5. Используйте np.where.  
Навыки: np.where, маски, логические условия, сравнение элементов с числом.  

Теория: логические массивы, выбор элементов по маске.  

4. Маска двумерной матрицы  

Создайте матрицу 5×5 случайных чисел. Выведите все элементы, которые больше 10 и меньше 50, используя маску.  

Навыки: булевы маски для матриц, индексация, логические операции с массивами (&).  

Теория: использование масок, индексация, выбор элементов по условию.  

5. Транспонирование и сумма  

Создайте матрицу 3×4, заполненную числами от 1 до 12.  
Выведите сумму каждой строки и каждого столбца. Используйте .T.  

Навыки: .T, np.sum с axis, работа с матрицами.  

Теория: транспонирование матрицы, суммирование по строкам и столбцам, NumPy массивы.  

6. Скалярное произведение  

Даны два вектора одинаковой длины. Найдите их скалярное произведение и косинусное расстояние между ними.  

Навыки: np.dot, вычисление скалярного произведения, косинусное расстояние.  

Теория: линейная алгебра, скалярное произведение векторов, векторизация.  

7. Выбор строк и столбцов  

Дана матрица 6×6. Выведите элементы из строк 1, 3, 5 и столбцов 0, 2, 4, используя индексацию через списки.  

Навыки: индексация через списки, выбор подмножеств матрицы.  

Теория: индексация массивов, извлечение подмножеств данных.  

8. Обратная матрица  

Дана квадратная матрица 3×3. Найдите её обратную и проверьте, что произведение исходной матрицы на обратную — единичная.  

Навыки: np.linalg.inv, матричное умножение @.  

Теория: линейная алгебра, обратная матрица, единичная матрица.  

9. Диагональ и сумма  

Дана квадратная матрица 4×4. Выведите её главную диагональ и сумму элементов диагонали.  

Навыки: np.diag, np.trace, работа с диагональю матрицы.  

Теория: линейная алгебра, матрицы, операции над диагональю.  

10. Логическая фильтрация  

Дан массив чисел. Выведите True/False для каждого элемента: True, если элемент больше среднего по массиву, и False — иначе. Используйте векторизацию.  

Навыки: векторизация, сравнение с условием, логические массивы.  

Теория: логические выражения, использование any/all, векторизация.  


1. Нормализация вектора  

Дан вектор чисел. Нормализуйте его так, чтобы сумма всех элементов была равна 1.  
Используйте NumPy и операции с массивами.  

Навыки: операции с вектором (деление на сумму элементов), NumPy массивы, поэлементные операции.  

Теория: линейная алгебра, векторы, скалярное умножение на число (сделано поэлементно).  

In [31]:
a = np.random.randint(1, 20, size = 5)
a

array([15,  5,  9, 19, 11], dtype=int32)

In [37]:
a / np.sum(a)


array([0.25423729, 0.08474576, 0.15254237, 0.3220339 , 0.18644068])

2. Скользящее среднее  

Дан массив температур за месяц (30 значений). Выведите массив скользящего среднего за 3 дня.  
Навыки: NumPy массивы, срезы, функции агрегации (np.mean), индексация.  

Теория: обработка данных, статистика, срезы массивов.  

100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the initialise.py module, then for each question you can query the answer or an hint with hint(n) or answer(n) for n question number.




     



     



     
11. Create a 3x3 identity matrix (★☆☆)


     
12. Create a 3x3x3 array with random values (★☆☆)


     
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


     
14. Create a random vector of size 30 and find the mean value (★☆☆)


     
15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


     
16. How to add a border (filled with 0's) around an existing array? (★☆☆)


     
17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


     
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


     
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


     
20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


     
21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


     
22. Normalize a 5x5 random matrix (★☆☆)


     
23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


     
24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


     
25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


     
26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


     
27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


     
28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


     
29. How to round away from zero a float array ? (★☆☆)


     
30. How to find common values between two arrays? (★☆☆)


     
31. How to ignore all numpy warnings (not recommended)? (★☆☆)


     
32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)


     
33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


     
34. How to get all the dates corresponding to the month of July 2016? (★★☆)


     
35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


     
36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


     
37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


     
38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


     
39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


     
40. Create a random vector of size 10 and sort it (★★☆)


     
41. How to sum a small array faster than np.sum? (★★☆)


     
42. Consider two random arrays A and B, check if they are equal (★★☆)


     
43. Make an array immutable (read-only) (★★☆)


     
44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


     
45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


     
46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)


     
47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


     
48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)


     
49. How to print all the values of an array? (★★☆)


     
50. How to find the closest value (to a given scalar) in a vector? (★★☆)


     
51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


     
52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


     
53. How to convert a float (32 bits) array into an integer (32 bits) array in place?


     
54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11


     
55. What is the equivalent of enumerate for numpy arrays? (★★☆)


     
56. Generate a generic 2D Gaussian-like array (★★☆)


     
57. How to randomly place p elements in a 2D array? (★★☆)


     
58. Subtract the mean of each row of a matrix (★★☆)


     
59. How to sort an array by the nth column? (★★☆)


     
60. How to tell if a given 2D array has null columns? (★★☆)


     
61. Find the nearest value from a given value in an array (★★☆)


     
62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)


     
63. Create an array class that has a name attribute (★★☆)


     
64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)


     
65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


     
66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


     
67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


     
68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


     
69. How to get the diagonal of a dot product? (★★★)


     
70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


     
71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)


     
72. How to swap two rows of an array? (★★★)


     
73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


     
74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


     
75. How to compute averages using a sliding window over an array? (★★★)


     
76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


     
77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


     
78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


     
79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)


     
80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)


     
81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


     
82. Compute a matrix rank (★★★)


     
83. How to find the most frequent value in an array?


     
84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


     
85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


     
86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


     
87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


     
88. How to implement the Game of Life using numpy arrays? (★★★)


     
89. How to get the n largest values of an array (★★★)


     
90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)


     
91. How to create a record array from a regular array? (★★★)


     
92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


     
93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


     
94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


     
95. Convert a vector of ints into a matrix binary representation (★★★)


     
96. Given a two dimensional array, how to extract unique rows? (★★★)


     
97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


     
98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


     
99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


     
100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

3. Create a null vector of size 10 (★☆☆)

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.size

10

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
b = np.arange(11)
for i in range(1,len(b)):
    if i % 5 == 0:
        b[i] = 1


b

array([0, 1, 2, 3, 4, 1, 6, 7, 8, 9, 1])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
d = np.random.randint(10, 49, 10)
d

array([29, 41, 48, 36, 30, 37, 43, 31, 32, 23], dtype=int32)

8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
d[::-1]

array([23, 32, 31, 43, 37, 30, 36, 48, 41, 29], dtype=int32)

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
f = [1,2,0,0,4,0]
for i in range(len(f)):
    if f[i] != 0:
        print(i)


0
1
4
