Линейная алгебра (LinAl)

1. Операции со скалярными массивами (векторами-упорядоченный набор чисел, массив)

а = (а1, а2, а3, ..., аn): 
а1 - материал дома,
а2 - соседи,
а3 - близость до метро и т.д.

Сложение, вычитание:
a +/- b =(a1,a2,...,an) + (b1,b2,...,bn) = (a1/-b1,a2/-b2,...,an/-bn)
вектор +/- вектор = вектор

def vector(list1,list2):
    return [a+b for a,b in zip(list1,list2)]

a =[1,2,3,4,5]
b =[6,2,3,4,5]
print(vector(a,b))

Умножение, деление:
1. Поэлементное умножение(произведение):
a*b = (a1,a2,...,an)*(b1,b2,...,bn) = (a1*b1,a2*b2,...,an*bn) 
вектор * вектор = вектор
2. Скалярное произведение(пример - косинусное расстояние, схожесть):
a*b = (a1,a2,...,an)*(b1,b2,...,bn) = a1*b1 + a2*b2 +...+ an*bn
вектор * вектор = скаляр
3. Векторное произведение

4. Деление:
a/b = (a1,a2,...,an)/(b1,b2,...,bn) = (a1/b1,a2/b2,...,an/bn) 
вектор / вектор = вектор


МАТРИЦЫ

Матрица размеров m x n, где m - число строк, n - число стобцов,
элементы матрицы.

Прямоугольная, квадратная, матрица-строка, матрица-столбец

Операции:

1. Умножение
2. Транспонирование (строки становятся столбцами) = в numpy есть функция: <имя матрицы>.T
3. Сложение, вычитание

!!! Чтобы открыть ноутбук: nbviewer.org

Чтобы загружить какую-нибудь библиотеку: !pip install <numpy>

NUMPY

Для векторов, матриц и многомерных наборов данных используется термин МАССИВ.

Функция np.array - создание списков,матриц (большая буква M)

<имя списка,матрицы>.shape или np.shape(<имя списка,матрицы>) - узнать размерность вектора или матрицы
<имя списка,матрицы>.size или np.size(<имя списка,матрицы>)- количество элементов в массиве

Массивы numpy статически типизированы и гомогенны (однородны), тип элемента определяется при создании массива, эффективны с точки зрения использования памяти, благодаря статической типизации быстрая реализация матем. функций(сложение, умножен...) с массивами может быть реализована на скомпилированном языке (Фортран, СИ).

<имя списка,матрицы>.dtype - узнать тип данных

<имя списка,матрицы> = np.array([[1,2],[3,4]], dtype=complex) - для явного указания типа данных внутри массива (dtype=)

Типы данных:
int,
float,
complex,
bool,
object
Можно определить тип данных в битах: например 'int64'

Функции для генерации:

1. <имя списка,матрицы> = np.arange(start, stop, step) - создание массива
2. <имя списка,матрицы> = np.linspace(0, 10, 25) - последовательность данных, равномерно расположенных на числовой прямой в заданном интервале, (start,stop, кол-во значений), в примере: 25 значений на интервале от 0 до 10
3. <имя списка,матрицы> = np.logspace(0, 10, 10, base=np.e) - последовательсть данных, которые равномерно расположены в заданном интервале на числовой прямой, но в лагорифм. масштабе
4. <имя списка,матрицы>, <имя списка,матрицы> = np.mgrid[0:5, 0:5] - специальный тип массива данных в numpy, который создает двухмерный массив 2D с аналогичными значениями, сетка массива, все одного размера и размерности, полезно для создания координат
5. np.random.rand(5,5) - генерация случайных матриц
   np.random.randn(5,5)  - генерация случайных матриц c нормальным распределением
6. создание диагональной матрицы:
   np.diag([1,2,3,4])
   np.diag([1,2,3,4], k = 1) # смещение матрицы направо 
7. Матрица только с нулями - np.zeros((3, 3)) 
   Матрица только с единицами- np.ones((3,3))

Открытие .csv и .tsv: data = np.genfromtxt('<название файла>')

Построение графиков через (import matplotlib.pyplot as plt):
fig, ax = plt.subplots(figsize= (14, 4))
ax.plot(data[:,0] + data[:,1]/12.0 + data[:,2]/365, data[:,5])

Сохранение данных в файле .csv:
np.savetxt('randommatrix.csv', M) - в скобках название файла и что сохраняет(матрица M)

Открыть файл .csv или в numpy или в командной строке:
!cat .\randommatrix.csv

Форматирование данных, количество знаков после запятой при сохранении:
np.savetxt('randommatrix.csv', M, fmt='%.5f')

У numpy свой формат данных .npy, полезен для хранения массивов и обращения к ним позже:
np.save('randommatrix.npy', M)

Загрузить сохраненный файл:
np.load('randommatrix.npy')


ИНДЕКСИРОВАНИЕ массивов

<имя списка>[i] или print(<имя списка>[i])
<имя матрицы>[m, n] или print(<имя матрицы>[m, n])

присвоить новое значение: <имя матрицы>[m, n] = x

Слайсинг - извлечение части массива (lower, upper, step):
A[1:3:2]
!!! Срезы изменяемы: A[1:3] = [-2, -3]

срез куска матрицы: 
A[1:4, 1:4]
A[::2] # каждый второй

Вытащить часть матрицы:
row_indices = [1, 2, 3] # столбцы
A[row_indices]

col_indices = [1, 2, -1] # колонки
A[row_indices, col_indices]

Создание маски для выбора определенных значений:
row_mask = np.array([True,False,True, True, False])
row_mask = np.array([1,0,1, 1, 0], dtype=bool)

mask = (5 < x) * (x < 7.5) # '*' = 'and'
indices = np.where(mask) - определить индексы масок

np.diag(A) - извлечение диагонали матрицы
np.diag(A,-1) - показывает, какая максимальная диагональ, которую можно извлечь

row_indices = [1, 3, 5]
np.take([-3, -2, -1,  0,  1,  2,  3], row_indices) или 
<имя списка>.take(row_indices) - получить значения индексов (row_indices) из списка


выбирает элементы из нескольких массивов
which = [1, 0, 1, 0] 
# choose перебирает (0,1,2,3) индексы чисел, в which указаны индексы самих списков
choices = [[-1, -2, -3, -4 ],[5, 6, 7, 8]]
np.choose(which, choices) # array([ 5, -2,  7, -4])



In [2]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# !pip install numpy

In [ ]:
v = np.array([1,2,3,4])
v

In [ ]:
M = np.array([[1,2],[3,4]]) # M большая-так обозначаются матрицы
M

In [ ]:
type(v), type(M)

In [ ]:
v.shape # hfpvthyjcnm

In [ ]:
M.shape

In [ ]:
M.size

In [ ]:
np.shape(M), np.size(M)

In [ ]:
M.dtype

In [ ]:
#M[0,0] = 'Hello' # invalid literal for int() with base 10: 'Hello'
# # нельзя использовать никакой другой тип данных, 
# # кроме тех, что были при создании массива

In [ ]:
M = np.array([[1,2],[3,4]], dtype=complex)
M

In [6]:
#x = np.arange(0, 10, 1)
#x
y = np.arange(0, 10, 2)
y

array([0, 2, 4, 6, 8])

In [ ]:
x = np.arange(-1,1,0.1) # -1 в ответе это степень, дробный шаг
x

In [ ]:
np.linspace(0, 10, 25) # 25 значений в интервале 1-10 

In [ ]:
np.logspace(0, 10, 10, base=np.e) #  

In [3]:
x, y = np.mgrid[0:5, 0:5]

In [4]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [5]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
np.random.rand(5,5) # генерация случаных матриц размером 5 на 5

In [ ]:
np.random.randn(5,5)

In [3]:
np.diag([1,2,3,4]) # диагональные матрицы

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag([1,2,3,4], k = 2) # диагональные матрицы,смещение матрицы направо

In [ ]:
np.zeros((3, 3)) # матрица только с нулями

In [ ]:
np.ones((3,3))

In [ ]:
#! pip install matplotlib

In [ ]:
data = np.genfromtxt('stockholm_td_adj.dat')

In [ ]:
data.shape

In [ ]:
fig, ax = plt.subplots(figsize= (14, 4))
ax.plot(data[:,0] + data[:,1]/12.0 + data[:,2]/365, data[:,5])

In [ ]:
np.savetxt('randommatrix.csv', M)

In [ ]:
# !cat .\randommatrix.csv

In [ ]:
np.savetxt('randommatrix.csv', M, fmt='%.5f')

In [ ]:
np.save('randommatrix.npy', M)

In [ ]:
np.load('randommatrix.npy')

In [ ]:
v

In [ ]:
print(v[0])

In [ ]:
M

In [ ]:
print(M[0,1])

In [ ]:
print(M[1])

In [ ]:
M[1, :]

In [ ]:
M[:, 1]

In [ ]:
M[0, 1] = 6

In [ ]:
M = np.array([[1, 2], [3, 4], [5,6]])

In [ ]:
M

In [ ]:
M[1, :] =0

In [ ]:
M

In [ ]:
M[:, 1] = -1

In [ ]:
M

In [ ]:
A = np.array([1,2,3,4,5])

In [ ]:
A[1:3]

In [ ]:
A[1:3] = [-2, -3]

In [ ]:
A

In [ ]:
A[::]

In [ ]:
A[::2] # каждое второе

In [ ]:
A[:3] # до третьего элемента

In [ ]:
A[3:] # с третьего элемента

In [ ]:
A[-1] # последний

In [ ]:
A[-3:] # до третьего с конца элемента направо

In [ ]:
A = np.array([[m*n*10 for n in range (5)] for m in range (5)])
A

In [ ]:
A[1:4, 1:4]

In [ ]:
A[::2] # каждый второй

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

In [ ]:
col_indices = [1, 2, -1]
A[row_indices, col_indices]

In [ ]:
B = np.array([n for n in range(5)])
B

In [ ]:
row_mask = np.array([True,False,True, True, False])
B[row_mask]

In [ ]:
row_mask = np.array([1,0,1, 1, 0], dtype=bool)
B[row_mask]

In [ ]:
x = np.arange(0, 10, 0.5)
x

In [ ]:
mask = (5 < x) * (x < 7.5) # '*' = 'and'
mask

In [ ]:
x[mask]

In [ ]:
indices = np.where(mask)
indices

In [ ]:
x[indices]

In [ ]:
A

In [ ]:
np.diag(A)

In [ ]:
np.diag(A,-1)

In [ ]:
v2 = np.arange(-3, 4)
v2

In [ ]:
row_indices = [1, 3, 5]
v2[row_indices]

In [ ]:
np.take([-3, -2, -1,  0,  1,  2,  3], row_indices)

In [ ]:
which = [1, 0, 1, 0] 
# choose перебирает (0,1,2,3) индексы чисел, в which указаны индексы самих списков
choices = [[-1, -2, -3, -4 ],[5, 6, 7, 8]]
np.choose(which, choices) # array([ 5, -2,  7, -4])